# Cambiar el puerto si el 8080 está ocupado
server.port=8080

# Aumentar el límite a 2GB por archivo y por petición
spring.servlet.multipart.max-file-size=2000MB
spring.servlet.multipart.max-request-size=2000MB

# Directorio donde se guardarán los archivos en tu tablet
# Asegúrate de crear esta carpeta o cambiar la ruta
app.upload.dir=./uploads
